export const dummyModule = [
  { modul_id: "5.2", name: "Test Modul 2" },
  { modul_id: "1.1", name: "Propädeutik" },
  { modul_id: "1.2", name: "Einführung in die Wissenschaft der Sozialen Arbeit" },
  { modul_id: "1.3", name: "OTIS/Sozialwirtschaft" },
  { modul_id: "1.4", name: "Wissenschaft der Sozialen Arbeit" },
  { modul_id: "1.5", name: "Forschungsmethoden" },
  { modul_id: "1.6", name: "Soziologische Grundlagen" },
  { modul_id: "1.7", name: "Psychologische Grundlagen" },
  { modul_id: "1.8", name: "Pädagogische Grundlagen" },
  { modul_id: "1.9", name: "Politikwissenschaftliche Grundlagen" },
  { modul_id: "1.10", name: "Medizinische Grundlagen" },
  { modul_id: "1.11", name: "Rechtsgrundlagen Sozialer Arbeit, Sozialrecht" },
  { modul_id: "1.12", name: "Familien-, Kinder- und Jugendhilferecht" },
  { modul_id: "1.13", name: "Entwicklung, Erziehung und Bildung" },
  { modul_id: "1.14", name: "Gesundheit und Krankheit" },
  { modul_id: "1.15", name: "Soziale Ungleichheit / Armut" },
  { modul_id: "1.16", name: "Ethik in der Sozialen Arbeit" },
  { modul_id: "2.1", name: "Kultur, Ästhetik, Bewegung (Praxisangebot)" },
  { modul_id: "2.1.", name: "Kultur, Ästhetik, Bewegung (Ringvorlesung)" },
  { modul_id: "2.2", name: "Gesprächsführung und Beobachtung, Präsentation und Moderation" },
  { modul_id: "2.3", name: "Arbeit mit Einzelnen und Familien" },
  { modul_id: "2.4", name: "Arbeit mit Gruppen" },
  { modul_id: "2.5", name: "Gemeinwesenarbeit" },
  { modul_id: "3.3", name: "PTT-Seminar" },
  { modul_id: "4.2.1", name: "Querschnitt: Abweichendes Verhalten und soziale Kontrolle" },
  { modul_id: "4.2.2", name: "Querschnitt: Soziale Arbeit mit und für ältere Menschen" },
  { modul_id: "4.2.3", name: "Querschnitt: Geschlechtssensible Konzepte" },
  { modul_id: "4.2.4", name: "Querschnitt: Praktische Erlebnispädagogik" },
  { modul_id: "4.2.5", name: "Querschnitt: Kulturelle Diversität" },
  { modul_id: "4.2.6", name: "Querschnitt: Internationale Soziale Arbeit" },
  { modul_id: "4.2.7", name: "Querschnitt: Medien in der Sozialen Arbeit" },
  { modul_id: "4.2.8", name: "Querschnitt: Sozial- und Jugendhilfeplanung, Organisation Sozialer Dienste" },
  { modul_id: "4.2.9", name: "Querschnitt: Digitale Soziale Arbeit/ Soziale Arbeit im virtuellen Raum" },
  { modul_id: "4.2.10", name: "Querschnitt: Grundlagen des Sozialmanagements" },
  { modul_id: "4.2.11", name: "Querschnitt: Onlineberatung" },
  { modul_id: "4.2.12", name: "Querschnitt: Soziale Arbeit und Menschenrechte" },
  { modul_id: "4.2.13", name: "Querschnitt: Kulturelle Bildung in der Sozialen Arbeit" },
  {
    modul_id: "4.2.14",
    name: "Querschnitt: Psychische Belastungen und Störungen - Schwerpunkt Kinder und Jugendliche",
  },
  { modul_id: "4.2.15", name: "Querschnitt: Psychische Belastungen und Störungen - Schwerpunkt Erwachsene" },
  { modul_id: "4.2.16", name: "Querschnitt: Freiwilligenmanagement" },
  { modul_id: "4.2.17", name: "Querschnitt: Forschung in der Sozialen Arbeit" },
  { modul_id: "4.2.18", name: "Querschnitt: StadtraumGesellschaft" },
  { modul_id: "4.4", name: "Allgemeinwissenschaftliche/ Fachbezogene Wahlpflichtfächer" },
];
export const dummyLv = [
  {
    id: "1",
    modul_id: "1.1",
    name: "Wissenschaftliches Arbeiten, Methoden und Strategien des Lernens",
  },
  {
    id: "2",
    modul_id: "1.1",
    name: "Informationstechnologien in der Sozialen Arbeit",
  },
  {
    id: "3",
    modul_id: "1.2",
    name: "Geschichte der Sozialen Arbeit",
  },
  {
    id: "4",
    modul_id: "1.2",
    name: "Einführung in die Theorien der Sozialen Arbeit",
  },
  {
    id: "5",
    modul_id: "1.3",
    name: "OTIS",
  },
  {
    id: "6",
    modul_id: "1.3",
    name: "Sozialwirtschaft",
  },
  {
    id: "7",
    modul_id: "1.4",
    name: "Theorien der Sozialen Arbeit",
  },
  {
    id: "8",
    modul_id: "1.5",
    name: "Forschungsmethoden",
  },
  {
    id: "9",
    modul_id: "1.11",
    name: "Rechtsgrundlagen Sozialer Arbeit",
  },
  {
    id: "10",
    modul_id: "1.6",
    name: "Ringvorlesung Soziologische Grundlagen",
  },
  {
    id: "11",
    modul_id: "1.6",
    name: "Seminar Soziologische Grundlagen",
  },
  {
    id: "12",
    modul_id: "1.7",
    name: "Psychologische Grundlagen",
  },
  {
    id: "13",
    modul_id: "1.8",
    name: "Ringvorlesung Pädagogische Grundlagen",
  },
  {
    id: "14",
    modul_id: "1.8",
    name: "Seminar Pädagogische Grundlagen",
  },
  {
    id: "15",
    modul_id: "1.9",
    name: "Ringvorlesung Politische Bildung",
  },
  {
    id: "16",
    modul_id: "1.9",
    name: "Seminar Politik und Sozialpolitik",
  },
  {
    id: "17",
    modul_id: "1.10",
    name: "Medizinische Grundlagen",
  },
  {
    id: "18",
    modul_id: "1.11",
    name: "Sozialrecht",
  },
  {
    id: "19",
    modul_id: "1.12",
    name: "Familienrecht",
  },
  {
    id: "20",
    modul_id: "1.12",
    name: "Kinder- und Jugendhilferecht",
  },
  {
    id: "21",
    modul_id: "1.13",
    name: "Entwicklung, Erziehung und Bildung",
  },
  {
    id: "22",
    modul_id: "1.14",
    name: "Gesundheit und Krankheit",
  },
  {
    id: "23",
    modul_id: "1.15",
    name: "Ringvorlesung",
  },
  {
    id: "24",
    modul_id: "1.15",
    name: "Projektbetreuung",
  },
  {
    id: "25",
    modul_id: "1.16",
    name: "Ethik in der Sozialen Arbeit",
  },
  {
    id: "26",
    modul_id: "2.1.",
    name: "Ringvorlesung Kultur, Ästhetik und Bewegung",
  },
  {
    id: "27",
    modul_id: "2.2",
    name: "Gesprächsführung und Beobachtung",
  },
  {
    id: "28",
    modul_id: "2.2",
    name: "Präsentation und Moderation",
  },
  {
    id: "29",
    modul_id: "2.3",
    name: "Arbeit mit Familien und Einzelnen",
  },
  {
    id: "30",
    modul_id: "2.4",
    name: "Arbeit mit Gruppen",
  },
  {
    id: "31",
    modul_id: "2.5",
    name: "Gemeinwesenarbeit",
  },
  {
    id: "32",
    modul_id: "4.2.1",
    name: "Querschnitt: Abweichendes Verhalten und soziale Kontrolle",
  },
  {
    id: "33",
    modul_id: "4.2.2",
    name: "Querschnitt: Soziale Arbeit mit und für ältere Menschen",
  },
  {
    id: "34",
    modul_id: "4.2.3",
    name: "Querschnitt: Geschlechtssensible Konzepte",
  },
  {
    id: "35",
    modul_id: "4.2.5",
    name: "Querschnitt: Kulturelle Diversität",
  },
  {
    id: "36",
    modul_id: "4.2.6",
    name: "Querschnitt: Internationale Soziale Arbeit",
  },
  {
    id: "37",
    modul_id: "4.2.7",
    name: "Querschnitt: Medien in der Sozialen Arbeit",
  },
  {
    id: "38",
    modul_id: "4.2.8",
    name: "Querschnitt: Sozial- und Jugendhilfeplanung, Organisation Sozialer Dienste",
  },
  {
    id: "39",
    modul_id: "4.2.9",
    name: "Querschnitt: Digitale Soziale Arbeit/ Soziale Arbeit im virtuellen Raum",
  },
  {
    id: "40",
    modul_id: "4.2.10",
    name: "Querschnitt: Grundlagen des Sozialmanagements",
  },
  {
    id: "41",
    modul_id: "4.2.11",
    name: "Querschnitt: Onlineberatung",
  },
  {
    id: "42",
    modul_id: "4.2.12",
    name: "Querschnitt: Soziale Arbeit und Menschenrechte",
  },
  {
    id: "43",
    modul_id: "4.2.13",
    name: "Querschnitt: Kulturelle Bildung in der Sozialen Arbeit",
  },
  {
    id: "44",
    modul_id: "4.2.14",
    name: "Querschnitt: Psychische Belastungen und Störungen - Schwerpunkt Kinder und Jugendliche",
  },
  {
    id: "45",
    modul_id: "4.2.15",
    name: "Querschnitt: Psychische Belastungen und Störungen - Schwerpunkt Erwachsene",
  },
  {
    id: "46",
    modul_id: "4.2.16",
    name: "Querschnitt: Freiwilligenmanagement",
  },
  {
    id: "47",
    modul_id: "4.2.17",
    name: "Querschnitt: Forschung in der Sozialen Arbeit",
  },
  {
    id: "48",
    modul_id: "4.2.18",
    name: "Querschnitt: StadtraumGesellschaft",
  },
  {
    id: "51",
    modul_id: "5.2",
    name: "Test LV 3",
  },
];
export const fakeData = [
  {
    id: "1",
    firstName: "Dylan",
    lastName: "Murray",
    city: "East Daphne",
    state: "Kentucky",
    managerId: null,
    subRows: [
      {
        id: "1.1",
        firstName: "Ervin",
        lastName: "Reinger",
        city: "South Linda",
        state: "West Virginia",
        managerId: "1",
        subRows: [
          {
            id: "1.1.1",
            firstName: "Jordane",
            lastName: "Homenick",
            city: "South Linda",
            state: "West Virginia",
            managerId: "1.1",
          },
          {
            id: "1.1.2",
            firstName: "Jordan",
            lastName: "Clarkson",
            city: "San Francisco",
            state: "California",
            managerId: "1.1",
          },
        ],
      },
      {
        id: "1.2",
        firstName: "Brittany",
        lastName: "McCullough",
        city: "Lincoln",
        state: "Nebraska",
        managerId: "1",
      },
    ],
  },
  {
    id: "2",
    firstName: "Raquel",
    lastName: "Kohler",
    city: "Columbus",
    state: "Ohio",
    managerId: null,
    subRows: [
      {
        id: "2.1",
        firstName: "Branson",
        lastName: "Frami",
        city: "Charleston",
        state: "South Carolina",
        managerId: "2",
      },
    ],
  },
  {
    id: "3",
    firstName: "Jordon",
    lastName: "Harris",
    city: "Perth",
    state: "Western Australia",
    managerId: null,
    subRows: [
      {
        id: "3.1",
        firstName: "Eldora",
        lastName: "Koch",
        city: "Perth",
        state: "Western Australia",
        managerId: "3",
      },
      {
        id: "3.2",
        firstName: "Glenn",
        lastName: "Crist",
        city: "Darwin",
        state: "Northern Territory",
        managerId: "3",
      },
    ],
  },
];

//50 us states array
export const usStates = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
  "Puerto Rico",
  "Western Australia",
  "Northern Territory",
  "South Australia",
  "Queensland",
];
